### ISSUE TITLE
It's not a typo

### ISSUE THREAD

**Issue by BlurryLight** [onestraw/epoll-example#2]
https://github.com/onestraw/epoll-example/issues/1

Accroding to the manpage[^1] (`man 2 fcntl`), `F_SETFD/F_GETFD` is only associated with the `FD_CLOEXEC` flag. It has non business of the `O_NONBLOCK` so the socke status will keep blocking when reading.

[^1]:http://man7.org/linux/man-pages/man2/fcntl.2.html

**Comment by SoonyangZhang** [comment]
Please fix such error. F_SETFD/F_GETFD the socket is in blocking status. I write my application and takes reference. It costs me about one hour to find such bug in setnonblocking fun.
